services:
  - type: web
    name: my-fastapi-app
    env: docker
    repo: https://github.com/yourname/yourrepo
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""     # optional override
    startCommand: ""     # optional override
    autoDeploy: true     # enable auto-deploy
    pullRequestPreviewsEnabled: true
    envVars:
      - key: ENV
        value: production
      - key: SECRET_KEY
        sync: false       # mark as secret, set in Render dashboard
